spring:
  data:
    redis:
      host: redis
      port: 6379
      timeout: 6000
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true
    try-it-out-enabled: true
logging:
  level:
    org.springdoc: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always